# Generated by Django 3.2.7 on 2023-04-23 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Quantity',
        ),
    ]
