# Generated by Django 3.2.7 on 2023-06-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230604_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_order',
            field=models.IntegerField(default=0),
        ),
    ]
