# Generated by Django 3.2.4 on 2023-04-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0018_product_user'),
        ('products', '0009_auto_20230426_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='cartproducts', to='shopping.Product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='wishlistproducts', to='shopping.Product'),
        ),
    ]
