# Generated by Django 3.2.4 on 2023-05-01 17:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0023_alter_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0010_auto_20230426_1032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='Wishist',
        ),
    ]
