# Generated by Django 3.2.7 on 2023-04-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_rename_unit_price_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='overall_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=1000, null=True),
        ),
    ]
