# Generated by Django 3.2.7 on 2023-04-24 19:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20230424_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='overall_rating',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='/images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
