# Generated by Django 3.2.4 on 2023-04-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='skills',
        ),
    ]
