# Generated by Django 3.2.7 on 2023-05-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_auto_20230527_1229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
