# Generated by Django 3.2.4 on 2023-04-25 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_auto_20230425_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
    ]
