# Generated by Django 3.2.7 on 2023-05-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_delete_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brands',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.DeleteModel(
            name='Brands',
        ),
        migrations.DeleteModel(
            name='Sizes',
        ),
    ]
