# Generated by Django 3.2.7 on 2023-05-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0017_product_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free',
            field=models.IntegerField(default=0),
        ),
    ]
