# Generated by Django 3.2.7 on 2023-06-04 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230604_0159'),
        ('shopping', '0020_shipping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
