# Generated by Django 3.2.4 on 2023-04-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0021_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
