# Generated by Django 3.2.7 on 2023-06-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0021_delete_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='special_offers',
        ),
    ]
