# Generated by Django 3.2.7 on 2023-06-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0022_auto_20230604_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
