# Generated by Django 3.2.7 on 2023-05-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_settinglang'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='SettingLang',
        ),
    ]
