# Generated by Django 3.2.7 on 2023-06-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.AddField(
            model_name='blog',
            name='discussion',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
