# Generated by Django 3.2.7 on 2023-05-30 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_categorylang_productlang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlang',
            name='product',
        ),
        migrations.RemoveField(
            model_name='settinglang',
            name='setting',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
        migrations.DeleteModel(
            name='CategoryLang',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='ProductLang',
        ),
        migrations.DeleteModel(
            name='SettingLang',
        ),
    ]
