# Generated by Django 3.2.7 on 2023-05-31 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230530_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='currency',
        ),
    ]
